version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - laravel

  postgres:
    image: postgres:9.5-alpine
    container_name: ${APP_NAME}-postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-php
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: ${APP_NAME}-composer
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - php
    networks:
      - laravel

  npm:
    image: node:14
    container_name: ${APP_NAME}-npm
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-artisan
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    working_dir: /var/www
    entrypoint: ['php', '/var/www/artisan']
    networks:
      - laravel
